'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FNSB_Facilities_Projects.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _126_Edit_32x32_72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("126_Edit_32x32_72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1532_Flag_system_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1532_Flag_system_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected funding record is already assigned to an active project. Choose OK to reassign the selected fund to the select project or Cancel to exit without reassigning..
        '''</summary>
        Friend ReadOnly Property ActiveFundingRecordAssignment() As String
            Get
                Return ResourceManager.GetString("ActiveFundingRecordAssignment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property add() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Annotate_Blocked_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Annotate_Blocked_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property basic_savebmp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basic_savebmp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_notebook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_notebook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Removing funding from this project may alter its budget amount. Select OK to continue removing funds or Cancel to exit without removing..
        '''</summary>
        Friend ReadOnly Property BudgetAlterStatement() As String
            Get
                Return ResourceManager.GetString("BudgetAlterStatement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete selected funding record?.
        '''</summary>
        Friend ReadOnly Property ConfirmDelete() As String
            Get
                Return ResourceManager.GetString("ConfirmDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are currently importing funding records. Select Yes to remove the selected rows from the current import or No to keep them in the list..
        '''</summary>
        Friend ReadOnly Property ConfirmDeleteImportNotSaved() As String
            Get
                Return ResourceManager.GetString("ConfirmDeleteImportNotSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The amount entered was not formatted correctly..
        '''</summary>
        Friend ReadOnly Property CurrencyFormatErrorMessage() As String
            Get
                Return ResourceManager.GetString("CurrencyFormatErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property err() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("err", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property F8() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("F8", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Flag_greenHS() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Flag_greenHS", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property FloppyDisk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FloppyDisk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are funding records currently imported but have not been assigned. These remaining imports can be assigned during the next import session. Continue to edit mode?.
        '''</summary>
        Friend ReadOnly Property FundingImportUnassigned() As String
            Get
                Return ResourceManager.GetString("FundingImportUnassigned", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to \\Tundra2\Workgrps\FNSB-db\Update\FacilitiesAndProjects\TrackingGlkeyAcceptions\tracking_exceptions.xml.
        '''</summary>
        Friend ReadOnly Property GlkeyAcceptionsFile() As String
            Get
                Return ResourceManager.GetString("GlkeyAcceptionsFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property help() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Image file not found. Check source location.
        '''</summary>
        Friend ReadOnly Property ImageNotFound() As String
            Get
                Return ResourceManager.GetString("ImageNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You&apos;re adding a new project to the inactive projects list. Select Ok to move to active projects mode and create a New record or Cancel to stay in Inactive Mode..
        '''</summary>
        Friend ReadOnly Property InactiveAdd() As String
            Get
                Return ResourceManager.GetString("InactiveAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This funding record is assigned to an inactive project. Select OK to reassign the selected fund or Cancel to exit without reassigning..
        '''</summary>
        Friend ReadOnly Property InactiveFundingRecordAssignment() As String
            Get
                Return ResourceManager.GetString("InactiveFundingRecordAssignment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property information() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("information", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property locked() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("locked", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property MC__AppWiz() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MC__AppWiz", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CSV files (*.csv)|*.csv.
        '''</summary>
        Friend ReadOnly Property OpenFileDialogCsvFilter() As String
            Get
                Return ResourceManager.GetString("OpenFileDialogCsvFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Works Project Tracking.
        '''</summary>
        Friend ReadOnly Property PrimaryDialogTitle() As String
            Get
                Return ResourceManager.GetString("PrimaryDialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property project() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("project", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A project has already been added but not saved. Select OK to save it and all other project changes before adding a new project or Cancel to keep working on the current new project..
        '''</summary>
        Friend ReadOnly Property ProjectsAddWarning() As String
            Get
                Return ResourceManager.GetString("ProjectsAddWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Works Projects.
        '''</summary>
        Friend ReadOnly Property PublicworksProjectHeader() As String
            Get
                Return ResourceManager.GetString("PublicworksProjectHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property RefreshDocViewHS() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("RefreshDocViewHS", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property reports() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("reports", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property save() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property Save16x16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Save16x16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save changes to funding records prior to importing?.
        '''</summary>
        Friend ReadOnly Property SaveFundsBeforeImport() As String
            Get
                Return ResourceManager.GetString("SaveFundsBeforeImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property textdoc() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("textdoc", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property warning() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
