//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNSB.Publicworks.Projects.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundingType
    {
        public System.Guid ppy_recordid { get; set; }
        public string fundsource { get; set; }
        public string fundname { get; set; }
    }
}
