//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNSB.Publicworks.Projects.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectManager
    {
        public ProjectManager()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int ppr_recordid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
}
