//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNSB.Publicworks.Projects.DataLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class publicworksEntities : DbContext
    {
        public publicworksEntities()
            : base("name=publicworksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ArchitectEngineer> ArchitectEngineers { get; set; }
        public DbSet<Consultant> Consultants { get; set; }
        public DbSet<Contractor> Contractors { get; set; }
        public DbSet<FundingType> FundingTypes { get; set; }
        public DbSet<Fund> Funds { get; set; }
        public DbSet<ProjectManager> ProjectManagers { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectType> ProjectTypes { get; set; }
        public DbSet<Secretary> Secretaries { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<OneSolutionFinance> OneSolutionFinances { get; set; }
    }
}
