//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNSB.Publicworks.Projects.DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int ppf_recordid { get; set; }
        public string ppf_funding { get; set; }
        public string ppf_department { get; set; }
        public string ppf_glkey { get; set; }
        public string ppf_glkey_name { get; set; }
        public Nullable<decimal> ppf_budget { get; set; }
        public Nullable<decimal> ppf_expenditures { get; set; }
        public Nullable<decimal> ppf_encumbrances { get; set; }
        public Nullable<decimal> ppf_balance { get; set; }
        public Nullable<int> ppm_recordid { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
