//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FNSB.Publicworks.Projects.Reports.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FNSB.Publicworks.Projects.Reports.Resources.MessageStrings", typeof(MessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project architect you have selected to delete is not assigned to any projects. Choose OK to delete the project architect or select Cancel to exit this process..
        /// </summary>
        internal static string ArchitectDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ArchitectDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project architect you have selected to delete is assigned to projects. Choose OK to delete the project architect and move their project assignments to Unassigned or select Cancel to exit this process..
        /// </summary>
        internal static string ArchitectDeleteConfirmWithProjectsMsg {
            get {
                return ResourceManager.GetString("ArchitectDeleteConfirmWithProjectsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Architect.
        /// </summary>
        internal static string ArchitectDialogHeader {
            get {
                return ResourceManager.GetString("ArchitectDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consultant you have selected to delete is not assigned to any projects. Choose OK to delete the consultant or select Cancel to exit this process..
        /// </summary>
        internal static string ConsultantDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ConsultantDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The consultant you have selected to delete is assigned to projects. Choose OK to delete the consultant and move their project assignments to Unassigned or select Cancel to exit this process..
        /// </summary>
        internal static string ConsultantDeleteConfirmWithProjectsMsg {
            get {
                return ResourceManager.GetString("ConsultantDeleteConfirmWithProjectsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Consultant.
        /// </summary>
        internal static string ConsultantDialogHeader {
            get {
                return ResourceManager.GetString("ConsultantDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contractor you have selected to delete is not assigned to any projects. Choose OK to delete the contractor or select Cancel to exit this process..
        /// </summary>
        internal static string ContractorDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ContractorDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contractor you have selected to delete is assigned to projects. Choose OK to delete the contractor and move their project assignments to Unassigned or select Cancel to exit this process..
        /// </summary>
        internal static string ContractorDeleteConfirmWithProjectsMsg {
            get {
                return ResourceManager.GetString("ContractorDeleteConfirmWithProjectsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Contractor.
        /// </summary>
        internal static string ContractorDialogHeader {
            get {
                return ResourceManager.GetString("ContractorDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing the glkey acception block will enable matching keys to import into Project Tracking. Select Yes to proceed or Cancel to exit without deleting..
        /// </summary>
        internal static string GlkeyAcceptionsVerifiyDelete {
            get {
                return ResourceManager.GetString("GlkeyAcceptionsVerifiyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project manager you have selected to delete is not assigned to any projects. Choose OK to delete the project manager or select Cancel to exit this process..
        /// </summary>
        internal static string ManagerDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("ManagerDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project manager you have selected to delete is assigned to projects. Choose OK to delete the project manager and move their project assignments to Unassigned or select Cancel to exit this process..
        /// </summary>
        internal static string ManagerDeleteConfirmWithProjectsMsg {
            get {
                return ResourceManager.GetString("ManagerDeleteConfirmWithProjectsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        internal static string ManagerDialogHeader {
            get {
                return ResourceManager.GetString("ManagerDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a matching entry in the database..
        /// </summary>
        internal static string SaveAddMatchingRecordFound {
            get {
                return ResourceManager.GetString("SaveAddMatchingRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record has been modified. Save changes before exiting?.
        /// </summary>
        internal static string SaveModifiedBeforeExit {
            get {
                return ResourceManager.GetString("SaveModifiedBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save entries as new record before exiting?.
        /// </summary>
        internal static string SaveNewBeforeExit {
            get {
                return ResourceManager.GetString("SaveNewBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project secretary you have selected to delete is not assigned to any projects. Choose OK to delete the project secretary or select Cancel to exit this process..
        /// </summary>
        internal static string SecretaryDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("SecretaryDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project secretary you have selected to delete is assigned to projects. Choose OK to delete the project secretary and move their project assignments to Unassigned or select Cancel to exit this process..
        /// </summary>
        internal static string SecretaryDeleteConfirmWithProjectsMsg {
            get {
                return ResourceManager.GetString("SecretaryDeleteConfirmWithProjectsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Secretary.
        /// </summary>
        internal static string SecretaryDialogHeader {
            get {
                return ResourceManager.GetString("SecretaryDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project type you have selected to delete is not assigned to any projects. Choose OK to delete the project type or select Cancel to exit this process..
        /// </summary>
        internal static string TypesDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("TypesDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project type you have selected to delete is assigned to projects. Choose OK to delete the project type and move their project assignments to Unassigned or select Cancel to exit this process..
        /// </summary>
        internal static string TypesDeleteConfirmWithProjectsMsg {
            get {
                return ResourceManager.GetString("TypesDeleteConfirmWithProjectsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type.
        /// </summary>
        internal static string TypesDialogHeader {
            get {
                return ResourceManager.GetString("TypesDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project user you have selected to delete is not assigned to any projects. Choose OK to delete the project user or select Cancel to exit this process..
        /// </summary>
        internal static string UserDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("UserDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project user you have selected to delete is assigned to projects. Choose OK to delete the project user and move their project assignments to Unassigned or select Cancel to exit this process..
        /// </summary>
        internal static string UserDeleteConfirmWithProjectsMsg {
            get {
                return ResourceManager.GetString("UserDeleteConfirmWithProjectsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project User.
        /// </summary>
        internal static string UserDialogHeader {
            get {
                return ResourceManager.GetString("UserDialogHeader", resourceCulture);
            }
        }
    }
}
